### PR TITLE
Support for 4.13

### PR DESCRIPTION
**Pull request by xclerc**
(The signature of a Typemod function had its signature changed,
the warning command-line handling was altered)

### CODE REVIEW

**Comment by akabe** [comment]
@xclerc Thank you for your patch and sorry for late reply.
Could you resolve a conflicted file and add a test case for 4.13 to .travis.yml as follows?

https://github.com/akabe/ocaml-jupyter/blob/master/.travis.yml#L51-L52

```patch
     - os: linux
       env: OCAML_VERSION=4.12.0 ARCHIMEDES=1
+    - os: linux
+      env: OCAML_VERSION=4.13.0 ARCHIMEDES=1
```

**Comment by xclerc** [comment]
Sorry about the conflict, work started from
the wrong branch. Everything should be in
order.

**Comment by akabe** [comment]
Thank you. Your patch is almost perfect, but `dune runtest` seems to fail. An error message in 4.13 has been changed a little. Could you fix the unit test?

The following patch works in my environment. 

```diff
diff --git a/test/repl/test_evaluation.ml b/test/repl/test_evaluation.ml
index 8d773e0..e01f473 100644
--- a/test/repl/test_evaluation.ml
+++ b/test/repl/test_evaluation.ml
@@ -165,7 +165,14 @@ let test__long_error_message ctxt =
 let test__exception ctxt =
   let status, actual = eval "failwith \"FAIL\"" in
   let msg =
-    if Sys.ocaml_version >= "4.12"
+    if Sys.ocaml_version >= "4.13"
+    then "\x1b[31mException: Failure \"FAIL\".\n\
+          Raised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\n\
+          Called from Stdlib__Fun.protect in file \"fun.ml\", line 33, characters 8-15\n\
+          Re-raised at Stdlib__Fun.protect in file \"fun.ml\", line 38, characters 6-52\n\
+          Called from Topeval.load_lambda in file \"toplevel/byte/topeval.ml\", line 89, characters 4-150\n\
+          \x1b[0m"
+    else if Sys.ocaml_version >= "4.12"
     then "\x1b[31mException: Failure \"FAIL\".\n\
           Raised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\n\
           Called from Stdlib__fun.protect in file \"fun.ml\", line 33, characters 8-15\n\
```

**Comment by xclerc** [comment]
The same patch works in my environment too, just pushed the diff.

**Comment by akabe** [comment]
@xclerc Thank you so much.

**Pull request merged**
