### PR TITLE
Fix directory path in the README

### PR DESCRIPTION
**Pull request by rinarakaki**
Slight correction about paths is made so could you check it out?

On another note, this package depends on `ocp-indent` when testing. Don't you need to add it to `depends` or `depopts` list in opam file or somewhere?

### CODE REVIEW

**Comment by rinarakaki** [comment]
Now checking Travis CI and the Python version of its image. 3.5+ is preferable if you choose one.

**Comment by akabe** [comment]
> On another note, this package depends on ocp-indent when testing. Don't you need to add it to depends or depopts list in opam file or somewhere?

No. ocp-indent code-formats `.ml` and `.mli` files in this package. opam doesn't need to re-check the code format because the files have been already checked by CI.

**Comment by rinarakaki** [comment]
Thank you @akabe for cheking and marging the PR!

About `ocp-indent`, when I first followed your [Contribution](https://github.com/akabe/ocaml-jupyter#contribution) instruction and commited my diff, consequently the hook activated and raised an error since I hadn't installed `ocp-indent`. It was mostly because I was an OCaml beginner and I wondered if the package should be required explicitly in somewhere like `opam` file but if you don't think so, it's completely no problem! Thanks

**Comment by akabe** [comment]
Sorry, I should explain installation of ocp-indent in the contribution section. I will add it to the next patch. Thanks.

**Pull request merged**
