### PR TITLE
Completion hints

### PR DESCRIPTION
**Pull request by akabe**
Issue: #47

### CODE REVIEW

**Comment by Naereen** [comment]
Hi @akabe, just wondering why this hasn't been merged yet?
Does it need more work?

**Comment by akabe** [comment]
@Naereen Yes. Front-end plugin for showing types is incomplete.

**Comment by Naereen** [comment]
OK. Can I try to help?

**Comment by akabe** [comment]
Thanks. Let me tell you about the details. Actually, development of this functionality is pending now because it is not so important and I have no time. The kernel-side patch has been already completed at this PR (only adding types to `metadata` of `complete_reply`), while the front-end nbextension is required for displaying `metadata` on Web browser as follows:



I implemented this at https://github.com/akabe/jupyter-completion-hint but this works only on Chrome, not on Firefox, Safari, etc. I think the idea of https://github.com/nteract/nteract/pull/1650 achieves cross-browser completion hinting.

I will retry to develop the nbextension at the end of this year. However I guess the major revision: it takes as much time as implementing from scratch. You can create it independently. If so, I will use your nbextension.

OCaml Jupyter kernel plans to send `complete_reply` message like

```json
{
  "status": "ok",
  "matches": ["fold_left", "fold_right", ...], // identifiers
  "cursor_start": 5,
  "cursor_end": 8,
  "metadata": { // usually metadata = {}, but we put hints here.
    "fold_left": {
      "hint_left": "V", // string shown at the left of an identifier (V for values, M for modules, etc.)
      "hint_right": "('a -> 'b -> 'a) -> 'a -> 'b list -> 'a" // string shown at the right of an identifier (type)
    },
    "fold_right": {
      "hint_left": "V",
      "hint_right": "('b -> 'a -> 'a) -> 'b list -> 'a -> 'a"
    }
  }
}
```

**Comment by Naereen** [comment]
I see, thanks for the details. I will first try your extension on Chrome, and see what blocks on other browsers, with the pointers you gave.

I don't think I will have time to write something from scratch unfortunately!

**Comment by Naereen** [comment]
On either Firefox or latest Chromium browser, I cannot get the extension to work:
```bash
Dec  1 12:42:15.208 error [ocaml-jupyer]: Unsupported request            
```
I will work on it later.
(also, `ocaml-jupyer` looks like a typo, `ocaml-jupyter` is preferred)

**Comment by akabe** [comment]
I will fix the typo later. Could you show me detailed logs as follows?

```
export LWT_LOG='* -> debug'
jupyter notebook
```

**Comment by Naereen** [comment]
Here:
```bash
Dec  1 12:52:00.971 info [ocaml-jupyer]: completion prefix = "print"
Dec  1 12:52:00.971 info [ocaml-jupyer]: Merlin command: ["/home/lilian/.opam/4.04.2/bin/ocamlmerlin","single","complete-prefix","-dot-merlin","./.merlin","-position","9","-prefix","print","-doc","n","-types","y"]
Dec  1 12:52:00.978 debug [ocaml-jupyer]: Merlin returns: {"class":"return","value":{"entries":[{"name":"print_bytes","kind":"Value","desc":"bytes -> unit","info":""},{"name":"print_char","kind":"Value","desc":"char -> unit","info":""},{"name":"print_endline","kind":"Value","desc":"string -> unit","info":""},{"name":"print_float","kind":"Value","desc":"float -> unit","info":""},{"name":"print_int","kind":"Value","desc":"int -> unit","info":""},{"name":"print_newline","kind":"Value","desc":"unit -> unit","info":""},{"name":"print_string","kind":"Value","desc":"string -> unit","info":""}],"context":null},"notifications":[],"timing":{"total":1.383,"query":0.7549999999999999,"reader":0.040000000000000036,"ppx":0.008000000000000007,"typer":0.5800000000000001,"error":0.0}}
Dec  1 12:52:00.978 debug [ocaml-jupyer]: SEND: HMAC=38cbd59e19a07081a9d19283abfa4d2d945bce91a5356a73e18b47ff097dedd9; header={"msg_id":"117209d7-2a08-4c20-a885-c9305e938336","msg_type":"complete_reply","session":"656E25C54A794F588A2246038DE8A2AC","date":"2017-12-01T11:52:00.9777Z","username":"username","version":"5.2"}; parent={"msg_id":"EE1A66E4D5774CF882AAFAB1149192B4","msg_type":"complete_request","session":"656E25C54A794F588A2246038DE8A2AC","username":"username","version":"5.2"}; content={"matches":["print_bytes","print_char","print_endline","print_float","print_int","print_newline","print_string"],"cursor_start":0,"cursor_end":5,"metadata":{},"status":"ok"}; metadata={}
```

**Comment by akabe** [comment]
Cannot `Unsupported request` bug be reproduced?

**Comment by Naereen** [comment]
```bash
Dec  1 12:57:09.831 debug [ocaml-jupyer]: RECV: HMAC=39cde01f1acd406ee33559aed51ddec1cbc6cbce130512f205a4fcb936a29b4c; header={"msg_id":"7E55DB723CBA4BF481648978D7197CC4","username":"username","session":"F5C25CE919974CBE97FC641F500745D6","msg_type":"inspect_request","version":"5.2"}; parent={}; content={"code":"print_endline","cursor_pos":13,"detail_level":0}; metadata={}
Dec  1 12:57:09.831 error [ocaml-jupyer]: Unsupported request
```

**Comment by akabe** [comment]
Oops! `inspect_request` is not supported... Do you think this is useful in OCaml?

**Comment by Naereen** [comment]
Sorry, I won't be able to spend more time on this right now.

**Comment by akabe** [comment]
OK. Thanks for trying!

**Comment by akabe** [comment]
I will support inspection for displaying types and documentation of an identifier, and rebase master to this branch.

**Comment by Naereen** [comment]
Hi @akabe, how is this going on? Still in progress or should we close it?

**Comment by akabe** [comment]
Sorry, I have no time to implement this functionality. I close this PR.

**Comment by Naereen** [comment]
No problem, thanks anyway @akabe.

**Pull request closed without merging**
