### PR TITLE
Support for 4.14.0 (beta1)

### PR DESCRIPTION
**Pull request by xclerc**
This pull request simply adds support for OCaml 4.14.0.
(Since it is only the first alpha, it is not clear whether it
should be considered for merge right now.)

### CODE REVIEW

**Comment by xclerc** [comment]
Note: the CI fails because the following line:
```
opam switch create . --no-install --packages 4.14.0~alpha1
```
results in:
```
opam: option `--packages': invalid element in list (`4.14.0~alpha1'): Invalid character in package name "4.14.0~alpha1"
```
It looks like the GitHub Actions for OCaml do not support
versions with a `~`; I will try and investigate.

**Comment by xclerc** [comment]
It turns out it is a known problem; thanks to @kit-ty-kate for
pointing to [this issue](https://github.com/ocaml/setup-ocaml/issues/232).
Happy to try and adapt the CI file if you think the workaround
is acceptable, but you may prefer to wait for 4.14 to be actually
published.

**Comment by akabe** [comment]
@xclerc Thank you for your patch and sorry for late reply.
It seems that your changes have no problems.

I will merge this PR after CI works.
I don't know release of either of 4.14 or setup-ocaml is fast.

**Comment by xclerc** [comment]
No worries! I have bumped the version to "beta1",
and tweaked the CI file in an attempt to make the
beta version installable.

**Comment by xclerc** [comment]
Sorry for the back and forth, it took me some
time to make the CI green. In particular, I did
not notice at first that some errors were not
due to this pull request but to a deprecation
in `Uuidm` (See commit https://github.com/akabe/ocaml-jupyter/pull/179/commits/f066c71971e0220030059b4ce0cbf7133ccb3070). Please let
know if you prefer to have this change in
another pull request.

**Comment by akabe** [comment]
Thanks for many trials and replacement of `Uuidm.create`.
I think your patch is good.
However I would like to know the probability that ocaml parsetree will change from 4.14.0~alpha1 to the official release of 4.14.0.
If I don't to worry about that, I will merge this PR and release to opam.

**Comment by kit-ty-kate** [comment]
> However I would like to know the probability that ocaml parsetree will change from 4.14.0~alpha1 to the official release of 4.14.0.

The latest version is not beta1 and the parsetree will **not** change.

**Comment by akabe** [comment]
Thank you!

**Pull request merged**
