### PR TITLE
OCaml 4.11 and cairo2 0.6 support

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Current jupyter does no compile with OCaml 4.11. This PR fixes it and also add support for cairo2 >= 0.6

### CODE REVIEW

**Comment by akabe** [comment]
@kit-ty-kate Thank you for your patch! Could you add ocaml 4.11 environment to .travis.yml?

**Comment by akabe** [comment]
@kit-ty-kate Any progress? `ppx_deriving_yojson` is incompatible with ocaml 4.11. This PR cannot be built on 4.11.

```
$ opam update
$ opam repo add beta https://github.com/ocaml/ocaml-beta-repository.git
$ opam switch install 4.11.0+trunk --repositories=default,beta
$ eval $(opam env)
$ ocaml -vnum
4.11.0+dev8-2020-06-17
$ git fetch origin pull/149/head:411
$ git checkout 411
$ opam pin add jupyter -y .
[jupyter.2.7.1: git]
[jupyter.2.7.1] synchronised from git+file:///Users/a14180/devel/ocaml/ocaml-jupyter#411
jupyter is now pinned to git+file:///Users/a14180/devel/ocaml/ocaml-jupyter#411 (version 2.7.1)

The following dependencies couldn't be met:
  - jupyter → ppx_deriving_yojson >= 3.0 → ocaml < 4.11.0
      base of this switch (use `--unlock-base' to force)

[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by akabe** [comment]
This PR seems inactive. If no replies were posted until July 11, I would close the PR and create a new PR containing only commit 5fac662.

**Comment by mseri** [comment]
@akabe `ppx_deriving_yojson` with support for ocaml 4.11 should be released soon. I can ping you here once that happens.

**Comment by akabe** [comment]
@mseri Thanks. I will try again after the release.

**Comment by kit-ty-kate** [comment]
oops, I'm really sorry for the lack of updates here. I had the changes locally but I forgot to push it.

For information, if all goes well OCaml 4.11 is going to be released next week.

**Comment by kit-ty-kate** [comment]
All green now.

**Comment by akabe** [comment]
@kit-ty-kate I'm sorry for late reply. Thank you!

**Pull request merged**
